openapi: "3.0.0"
info:
  version: 1.0.3
  title: SwaggerBake Demo
  license:
    name: MIT
servers:
  - url: /
paths:

components:
  schemas:
    Exception:
      type: object
      properties:
        code:
          type: integer
          example: 500
        url:
          type: string
          example: /url/path
        message:
          type: string
          example: Internal Error
    OperationResult:
      type: object
      properties:
        result:
          type: boolean
        message:
          type: string
