openapi: "3.0.0"
info:
  version: 1.4.2
  title: SwaggerBake Demo
  license:
    name: MIT
servers:
  - url: /
paths:
  '/films/{film_id}/film-texts':
    get:
      summary: Index method
      description: 'This shows using the definitions from YML instead of reading from your cake routes and models.
      YML definitions take precedence over cake routes and models.'
      tags:
        - Film Texts
      operationId: 'filmtexts:index'
      parameters:
        - name: film_id
          in: path
          required: true
          schema:
            description: ''
            type: string
          deprecated: false
          allowEmptyValue: false
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilmTexts'
        '500':
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
      deprecated: false
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: API-KEY
  schemas:
    FilmTexts:
      description: 'Model loaded from YML instead'
      type: array
      items:
        $ref: '#/components/schemas/FilmText'
    FilmText:
      description: 'Model loaded from YML instead'
      type: object
      required:
        - film_id
        - title
      properties:
        uuid:
          type: string
          format: ''
          readOnly: true
          writeOnly: false
        film_id:
          type: integer
          format: ''
          readOnly: false
          writeOnly: false
        title:
          type: string
          format: ''
          readOnly: false
          writeOnly: false
        description:
          type: string
          format: ''
          readOnly: false
          writeOnly: false
    Exception:
      type: object
      properties:
        code:
          type: integer
          example: 500
        url:
          type: string
          example: /url/path
        message:
          type: string
          example: Internal Error
      xml:
        name: response
    OperationResult:
      type: object
      properties:
        result:
          type: boolean
        message:
          type: string
      xml:
        name: response
    CityExtended:
      description: 'City with extended information including Country'
      type: object
      allOf:
        - $ref: '#/components/schemas/City'
        - type: object
          properties:
            country:
              $ref: '#/components/schemas/Country'

