openapi: "3.0.0"
info:
  version: 2.2.*
  title: SwaggerBake Demo
  description: |
    This is a sample SwaggerBake demo server. You can find more information at
    [https://github.com/cnizzardini/cakephp-swagger-bake](https://github.com/cnizzardini/cakephp-swagger-bake).

    **NOTE:** *The demo database gets refreshed once per day. Deletes are prevented.*

    Scroll down to explore the demo.

  license:
    name: MIT License
paths:
  '/examples/':
    get:
      summary: Index method
      description: 'This shows using the definitions from YML instead of reading from your cake routes and models.
      YML definitions take precedence over cake routes and models.'
      tags:
        - Examples
      operationId: 'examples:index'
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
components:
  securitySchemes:
    ApiKey:
      description: See `/examples/api-key-example` for demo/example.
      type: apiKey
      in: header
      name: API-KEY
  schemas:
    Exception:
      type: object
      properties:
        code:
          type: integer
          example: 500
        url:
          type: string
          example: /url/path
        message:
          type: string
          example: Internal Error
      xml:
        name: response
    OperationResult:
      type: object
      properties:
        result:
          type: boolean
        message:
          type: string
      xml:
        name: response
    Place:
      description: 'Country object'
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          example: 'countries'
        attributes:
          type: object
          properties:
            yitzo_country_code:
              type: string
              example: 'ES'
            is_active:
              type: boolean
              example: true
        relationships:
          type: object
          properties:
            description:
              type: array
              items:
                $ref: '#/components/schemas/CountryDescription'
    CountryDescription:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
          example: 'a description'
x-demo:
  components:
    parameters:
      anotherHeader:
        name: x_demo_another_header
        in: header
        required: false
        schema:
          type: sctring
